# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleUsingLibrary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleUsingLibrary
  
   #pod 'FinalLibrary', :git => 'https://github.com/sandipermata/FinalLibrary.git'
    #pod 'SandiLibrary', :path => '../SandiLibrary'
    pod 'SandiLibrary', :git => 'https://https://github.com/sandipermata/FinalLibrary.git'
    
end
